### ISSUE TITLE
Calling bandit_choose from within controller

### ISSUE THREAD

**Issue by ghost** [bmuller/bandit#12]
If I understand the documentation correctly, I should be able to call the `bandit_choose`, `bandit_sticky_choose`, etc. methods from within a controller, but when I try that, I get a NoMethodError: "undefined method `bandit_choose'."

Am I doing something wrong?

For what it's worth, I'd like to create a helper method in ApplicationController to sticky-choose and collect test variants when the user first hits the site.  Something like

```
def bandits
    @bandits ||= Bandit.experiments.inject({}) { |m, e| m[e.name] = bandit_sticky_choose(e.name); m }
end
```

...so I can more easily pass the selected test variants to GoogleAnalytics for conversion-tracking purposes.

thanks,

Jacob

**Comment by trisignia** [comment]
I think I answered my own question: I can call the bandit_choose methods from controllers if I include the view concerns in ActionController.  Adding this to config/initializers/bandit.rb did the trick:

```
require 'action_view'
ActionController::Base.send :include, Bandit::ViewConcerns
```

**Comment by bmuller** [comment]
Via pull request 13 - this should be done automatically now (in version 0.0.10).
