### ISSUE TITLE
Not getting most recent commit?

### ISSUE THREAD

**Issue by bstingle** [bmuller/bandit#3]
Hi, 

Cool gem! 

I put  "gem 'bandit' "  in my gemfile, but I don't seem to get the most recent commit. specifically, it's lacking the controller functionality, which is what I want to use!   I tried including a specific commit in my gemfile, but that's wrecking havoc with my IDE (rubymine).  Is there anything I'm doing wrong that the vanilla gem requirement is not calling this updated commit?  thanks!

Benjamin

**Comment by bmuller** [comment]
I incremented the version for you.  It should pull in version 0.0.6 now.

**Comment by bstingle** [comment]
Thanks!

On Mon, Apr 16, 2012 at 5:56 AM, Brian Muller <
reply@reply.github.com

> wrote:
> 
> I incremented the version for you.  It should pull in version 0.0.6 now.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/bmuller/bandit/issues/3#issuecomment-5151542

## 

Benjamin Stingle http://flavors.me/bstingle
