### ISSUE TITLE
Allow for newer redis client versions

### ISSUE THREAD

**Issue by ethul** [bmuller/bandit#4]
hi,

I am wondering if it would be feasible to allow for newer versions of the redis client, so instead of:

``` ruby
s.add_dependency("redis", "= 2.2.2")
```

maybe

``` ruby
s.add_dependency("redis", ">= 2.2.2")
```

Thanks!
 -Eric

**Comment by bmuller** [comment]
done

**Comment by ethul** [comment]
Sweet! Thanks for the quick turn-around.
