### ISSUE TITLE
Deprecation Warnings

### ISSUE THREAD

**Issue by dgilperez** [bmuller/bandit#5]
Hi!

I'm seeing this deprecation warnings in my Rails 3.2.2 app: 

`DEPRECATION WARNING: The InstanceMethods module inside ActiveSupport::Concern will be no longer included automatically. Please define instance methods directly in Bandit::ControllerConcerns instead. (called from include at /Users/dgilperez/.rvm/gems/ruby-1.9.2-p290/bundler/gems/bandit-8383abdca2e1/lib/bandit.rb:67)`
`DEPRECATION WARNING: The InstanceMethods module inside ActiveSupport::Concern will be no longer included automatically. Please define instance methods directly in Bandit::ViewConcerns instead. (called from include at /Users/dgilperez/.rvm/gems/ruby-1.9.2-p290/bundler/gems/bandit-8383abdca2e1/lib/bandit.rb:70)`

Anything to worry about?

Thanks for sharing this gem, I'm looking forward to use it in my app. I'll let you know about successes!

Regards!

**Comment by bmuller** [comment]
Hey - what version of bandit are you using (or are you using what's on github)?

**Comment by dgilperez** [comment]
I'm on your last version of the code. I'm currently extending the gem to support Dalli (memcached client) on my fork, but this issue happens also in master.
